### ISSUE TITLE
lost for words

### ISSUE THREAD

**Issue by junlee-3** [archibaldh/MyNotionWidgets#1]
This is the worst code ive ever seen archie, i thought you implemented an API or something like that to fetch data but NO!!! YOURE JUST WRITING A BUNCH OF IF STATEMENTS TO SHOW DIFFERENT SCREENSHOTS OF YOUR TIMETABLE. ARE YOU FR????

do better archibald hansen

**Comment by archibaldh** [comment]
bro what API did you expect me to use for my CGS Timetable? Are you stupid or something bro? You go implement an API to do the same job easier and more effectively I dare you
